#!/usr/bin/env bash
# ci/ci.sh - CI workflow file generator
#
# Incorporates patterns from:
#   ghazzor/Xanmod-Kernel-Builder      - GitHub Actions Clang/LLVM workflow
#   tsirysndr/vmlinux-builder          - Multi-arch CI, release artifact upload
#   rizalmart/puppy-linux-kernel-maker - Branch-per-version workflow pattern
#   Biswa96/android-kernel-builder     - Android CI workflow
#   osresearch/linux-builder           - Appliance/firmware CI

ci_usage() {
    cat <<EOF
lkf ci - Generate CI workflow files

USAGE: lkf ci [options]

OPTIONS:
  --provider <name>   CI provider: github, gitlab, forgejo [default: github]
  --arch <list>       Comma-separated architectures [x86_64]
  --flavor <name>     Kernel flavor: mainline, xanmod, android [mainline]
  --llvm              Include LLVM/Clang build
  --lto <mode>        LTO mode: none, thin, full [none]
  --output <path>     Output file path [auto per provider]
  --release           Include release artifact upload step
  --matrix            Generate a matrix build (one job per arch)

EXAMPLES:
  lkf ci --arch x86_64,aarch64 --llvm --lto full --release
  lkf ci --provider gitlab --arch x86_64,aarch64 --llvm
  lkf ci --provider forgejo --flavor xanmod --release
  lkf ci --flavor android --arch aarch64 --output .github/workflows/android.yml
EOF
}

ci_main() {
    local provider="github" arch_list="x86_64" flavor="mainline"
    local llvm=0 lto="none" output="" release=0 matrix=0

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --provider) provider="$2"; shift 2 ;;
            --arch)     arch_list="$2"; shift 2 ;;
            --flavor)   flavor="$2"; shift 2 ;;
            --llvm)     llvm=1; shift ;;
            --lto)      lto="$2"; shift 2 ;;
            --output)   output="$2"; shift 2 ;;
            --release)  release=1; shift ;;
            --matrix)   matrix=1; shift ;;
            --help|-h)  ci_usage; return 0 ;;
            *) lkf_die "Unknown option: $1" ;;
        esac
    done

    case "${provider}" in
        github)  ci_generate_github  "${arch_list}" "${flavor}" "${llvm}" \
                     "${lto}" "${output}" "${release}" "${matrix}" ;;
        gitlab)  ci_generate_gitlab  "${arch_list}" "${flavor}" "${llvm}" \
                     "${lto}" "${output}" "${release}" "${matrix}" ;;
        forgejo) ci_generate_forgejo "${arch_list}" "${flavor}" "${llvm}" \
                     "${lto}" "${output}" "${release}" "${matrix}" ;;
        *) lkf_die "Unsupported CI provider: ${provider}" ;;
    esac
}

ci_generate_github() {
    local arch_list="$1" flavor="$2" llvm="$3" lto="$4"
    local output="${5:-.github/workflows/kernel.yml}"
    local release="$6" matrix="$7"

    lkf_ensure_dir "$(dirname "${output}")"

    IFS=',' read -ra arches <<< "${arch_list}"

    # Build lkf build command flags
    local build_flags="--flavor ${flavor}"
    [[ "${llvm}" -eq 1 ]] && build_flags+=" --llvm"
    [[ "${lto}" != "none" ]] && build_flags+=" --lto ${lto}"

    lkf_step "Generating GitHub Actions workflow: ${output}"

    cat > "${output}" <<YAML
# Generated by lkf ci
# Kernel flavor: ${flavor} | LLVM: ${llvm} | LTO: ${lto}
# Architectures: ${arch_list}

name: Kernel Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*', '[0-9]*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel version (e.g. 6.12)'
        required: true
        default: '6.12'

jobs:
YAML

    if [[ "${matrix}" -eq 1 ]]; then
        # Matrix build
        local arch_json
        arch_json=$(printf '"%s",' "${arches[@]}")
        arch_json="[${arch_json%,}]"

        cat >> "${output}" <<YAML
  build:
    name: Build (\${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ${arch_json}

    steps:
      - uses: actions/checkout@v4

      - name: Install lkf
        run: |
          git clone https://github.com/your-org/lkf /opt/lkf
          echo "/opt/lkf" >> \$GITHUB_PATH

      - name: Install build dependencies
        run: lkf build --install-deps --version \${{ github.event.inputs.kernel_version || '6.12' }} ${build_flags} --arch \${{ matrix.arch }} --stop-after download

      - name: Build kernel
        run: |
          lkf build \\
            --version \${{ github.event.inputs.kernel_version || '6.12' }} \\
            ${build_flags} \\
            --arch \${{ matrix.arch }} \\
            --threads \$(nproc) \\
            --build-dir build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-\${{ matrix.arch }}-\${{ github.event.inputs.kernel_version || '6.12' }}
          path: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
            build/bootx64.efi
          if-no-files-found: warn
YAML
    else
        # Individual jobs per arch
        for arch in "${arches[@]}"; do
            local runner="ubuntu-latest"
            local cross_flag=""
            [[ "${arch}" == "aarch64" ]] && cross_flag="--cross aarch64-linux-gnu-"

            cat >> "${output}" <<YAML
  build-${arch}:
    name: Build (${arch})
    runs-on: ${runner}

    steps:
      - uses: actions/checkout@v4

      - name: Install lkf
        run: |
          git clone https://github.com/your-org/lkf /opt/lkf
          echo "/opt/lkf" >> \$GITHUB_PATH

YAML
            if [[ "${llvm}" -eq 1 ]]; then
                cat >> "${output}" <<YAML
      - name: Install LLVM
        run: |
          wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 19
          sudo apt-get install -y clang-19 lld-19 llvm-19
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/lld-19 100

YAML
            fi

            cat >> "${output}" <<YAML
      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \\
            build-essential bison flex libncurses-dev libssl-dev \\
            libelf-dev bc lz4 zstd rsync cpio xz-utils bzip2 \\
            dwarves pahole debhelper
YAML
            if [[ "${arch}" == "aarch64" ]]; then
                cat >> "${output}" <<YAML
          sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
YAML
            fi

            cat >> "${output}" <<YAML

      - name: Build kernel
        run: |
          lkf build \\
            --version \${{ github.event.inputs.kernel_version || '6.12' }} \\
            ${build_flags} \\
            --arch ${arch} \\
            ${cross_flag} \\
            --threads \$(nproc) \\
            --build-dir build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${arch}-\${{ github.event.inputs.kernel_version || '6.12' }}
          path: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
          if-no-files-found: warn

YAML
        done
    fi

    # Release job
    if [[ "${release}" -eq 1 ]]; then
        cat >> "${output}" <<YAML
  release:
    name: Create Release
    needs: [$(printf 'build-%s, ' "${arches[@]}" | sed 's/, $//')]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create checksums
        run: |
          find artifacts/ -type f | sort | xargs sha256sum > SHA256SUMS

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*
            SHA256SUMS
          generate_release_notes: true
YAML
    fi

    lkf_info "GitHub Actions workflow written to: ${output}"
}

# ── GitLab CI generator ───────────────────────────────────────────────────────

ci_generate_gitlab() {
    local arch_list="$1" flavor="$2" llvm="$3" lto="$4"
    local output="${5:-.gitlab-ci.yml}"
    local release="$6" matrix="$7"

    lkf_ensure_dir "$(dirname "${output}")"
    IFS=',' read -ra arches <<< "${arch_list}"

    local build_flags="--flavor ${flavor}"
    [[ "${llvm}" -eq 1 ]] && build_flags+=" --llvm"
    [[ "${lto}" != "none" ]] && build_flags+=" --lto ${lto}"

    lkf_step "Generating GitLab CI pipeline: ${output}"

    cat > "${output}" <<YAML
# Generated by lkf ci --provider gitlab
# Kernel flavor: ${flavor} | LLVM: ${llvm} | LTO: ${lto}
# Architectures: ${arch_list}

default:
  image: ubuntu:24.04
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends
        build-essential bison flex libncurses-dev libssl-dev
        libelf-dev bc lz4 zstd rsync cpio xz-utils bzip2
        dwarves pahole git curl ca-certificates
    - git clone https://github.com/your-org/lkf /opt/lkf
    - export PATH="/opt/lkf:\$PATH"

variables:
  KERNEL_VERSION:
    value: "6.12"
    description: "Kernel version to build"

stages:
  - build
$([ "${release}" -eq 1 ] && echo "  - release")

YAML

    for arch in "${arches[@]}"; do
        local tags="x86_64"
        local cross_pkg=""
        local cross_flag=""
        if [[ "${arch}" == "aarch64" ]]; then
            tags="aarch64"
            cross_pkg="gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu"
            cross_flag="--cross aarch64-linux-gnu-"
        fi

        cat >> "${output}" <<YAML
build:${arch}:
  stage: build
  tags:
    - ${tags}
  script:
YAML
        if [[ -n "${cross_pkg}" ]]; then
            cat >> "${output}" <<YAML
    - apt-get install -y ${cross_pkg}
YAML
        fi
        if [[ "${llvm}" -eq 1 ]]; then
            cat >> "${output}" <<YAML
    - |
      curl -fsSL https://apt.llvm.org/llvm.sh | bash -s -- 19
      apt-get install -y clang-19 lld-19 llvm-19
      update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
YAML
        fi
        cat >> "${output}" <<YAML
    - |
      lkf build \\
        --version "\${KERNEL_VERSION}" \\
        ${build_flags} \\
        --arch ${arch} \\
        ${cross_flag} \\
        --threads \$(nproc) \\
        --build-dir build/
  artifacts:
    name: "kernel-${arch}-\${KERNEL_VERSION}"
    paths:
      - build/*.deb
      - build/*.rpm
      - build/*.tar.gz
    expire_in: 7 days
    when: always

YAML
    done

    if [[ "${release}" -eq 1 ]]; then
        local needs_list
        needs_list=$(printf '"build:%s", ' "${arches[@]}")
        needs_list="[${needs_list%, }]"

        cat >> "${output}" <<YAML
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: ${needs_list}
  rules:
    - if: '\$CI_COMMIT_TAG'
  script:
    - find build/ -type f | sort | xargs sha256sum > SHA256SUMS
  release:
    tag_name: '\$CI_COMMIT_TAG'
    name: 'Kernel \$CI_COMMIT_TAG'
    description: 'Kernel build \$CI_COMMIT_TAG'
  artifacts:
    paths:
      - SHA256SUMS
YAML
    fi

    lkf_info "GitLab CI pipeline written to: ${output}"
}

# ── Forgejo / Gitea CI generator ──────────────────────────────────────────────
#
# Forgejo Actions uses the same workflow syntax as GitHub Actions (act-based),
# so the output is structurally identical.  Differences:
#   - Default output path is .forgejo/workflows/kernel.yml
#   - Uses forgejo-runner tags instead of GitHub-hosted runners
#   - Release step uses the Forgejo release API via curl rather than
#     softprops/action-gh-release (which requires github.com)

ci_generate_forgejo() {
    local arch_list="$1" flavor="$2" llvm="$3" lto="$4"
    local output="${5:-.forgejo/workflows/kernel.yml}"
    local release="$6" matrix="$7"

    lkf_ensure_dir "$(dirname "${output}")"
    IFS=',' read -ra arches <<< "${arch_list}"

    local build_flags="--flavor ${flavor}"
    [[ "${llvm}" -eq 1 ]] && build_flags+=" --llvm"
    [[ "${lto}" != "none" ]] && build_flags+=" --lto ${lto}"

    lkf_step "Generating Forgejo Actions workflow: ${output}"

    cat > "${output}" <<YAML
# Generated by lkf ci --provider forgejo
# Kernel flavor: ${flavor} | LLVM: ${llvm} | LTO: ${lto}
# Architectures: ${arch_list}
#
# Requires a self-hosted Forgejo runner with the 'lkf' label.
# Register one with: forgejo-runner register --labels lkf

name: Kernel Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*', '[0-9]*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Kernel version (e.g. 6.12)'
        required: true
        default: '6.12'

jobs:
YAML

    for arch in "${arches[@]}"; do
        local runner="lkf"
        local cross_step=""
        local cross_flag=""
        if [[ "${arch}" == "aarch64" ]]; then
            cross_step="          sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu"
            cross_flag="--cross aarch64-linux-gnu-"
        fi

        cat >> "${output}" <<YAML
  build-${arch}:
    name: Build (${arch})
    runs-on: ${runner}

    steps:
      - uses: actions/checkout@v3

      - name: Install lkf
        run: |
          git clone https://github.com/your-org/lkf /opt/lkf
          echo "/opt/lkf" >> \$GITHUB_PATH

      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \\
            build-essential bison flex libncurses-dev libssl-dev \\
            libelf-dev bc lz4 zstd rsync cpio xz-utils bzip2 \\
            dwarves pahole debhelper
YAML
        if [[ -n "${cross_step}" ]]; then
            printf '%s\n' "${cross_step}" >> "${output}"
        fi
        if [[ "${llvm}" -eq 1 ]]; then
            cat >> "${output}" <<YAML

      - name: Install LLVM
        run: |
          curl -fsSL https://apt.llvm.org/llvm.sh | sudo bash -s -- 19
          sudo apt-get install -y clang-19 lld-19 llvm-19
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
YAML
        fi

        cat >> "${output}" <<YAML

      - name: Build kernel
        run: |
          lkf build \\
            --version \${{ github.event.inputs.kernel_version || '6.12' }} \\
            ${build_flags} \\
            --arch ${arch} \\
            ${cross_flag} \\
            --threads \$(nproc) \\
            --build-dir build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${arch}-\${{ github.event.inputs.kernel_version || '6.12' }}
          path: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
          if-no-files-found: warn

YAML
    done

    if [[ "${release}" -eq 1 ]]; then
        local needs_list
        needs_list=$(printf 'build-%s, ' "${arches[@]}")
        needs_list="[${needs_list%, }]"

        cat >> "${output}" <<YAML
  release:
    name: Create Release
    needs: ${needs_list}
    runs-on: lkf
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Create checksums
        run: find artifacts/ -type f | sort | xargs sha256sum > SHA256SUMS

      - name: Publish Forgejo release
        env:
          FORGEJO_TOKEN: \${{ secrets.FORGEJO_TOKEN }}
          FORGEJO_URL: \${{ github.server_url }}
        run: |
          TAG="\${GITHUB_REF#refs/tags/}"
          # Create the release
          curl -fsSL -X POST \\
            -H "Authorization: token \${FORGEJO_TOKEN}" \\
            -H "Content-Type: application/json" \\
            "\${FORGEJO_URL}/api/v1/repos/\${GITHUB_REPOSITORY}/releases" \\
            -d "{\"tag_name\":\"\${TAG}\",\"name\":\"Kernel \${TAG}\",\"body\":\"Kernel build \${TAG}\"}"
YAML
    fi

    lkf_info "Forgejo Actions workflow written to: ${output}"
}
